### ISSUE TITLE
Devise github workflow to have PRs into epic branches run CI tests

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher#3229]
It would be nice if pull requests into epic branches would run CI tests (python at least, maybe others).

Perhaps the branch filter for our CI builds can be something like:
```
on:
  pull_request:
    branches:
      - main
      - development
      - epic-*
```

So any PR into an epic branch that matches the epic glob pattern eg. `epic-coordinator-13` will then have CI tests run.

Open to other ideas.
